# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: json dicts can be added to the conn_extra field as yaml key value pairs. See the example below.

# For more information, refer to our docs: https://docs.astronomer.io/develop-project#configure-airflow_settingsyaml-local-development-only
# For questions, reach out to: https://support.astronomer.io
# For issues create an issue ticket here: https://github.com/astronomer/astro-cli/issues

airflow:
  connections:
    - conn_id: getting_json_file
      conn_type: fs
      conn_host:
      conn_schema:
      conn_login:
      conn_password:
      conn_port: 
      conn_extra:
        path: include/data/new
    - conn_id: conn_postgres
      conn_type: postgres
      conn_host: localhost
      conn_schema: my_project
      conn_login: postgres
      conn_password: postgres
      conn_port: 5432
      conn_extra:
        path: 
  pools:
    - pool_name:
      pool_slot:
      pool_description:
  variables:
    - variable_name:
      variable_value: