# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: json dicts can be added to the conn_extra field as yaml key value pairs. See the example below.

# For more information, refer to our docs: https://docs.astronomer.io/develop-project#configure-airflow_settingsyaml-local-development-only
# For questions, reach out to: https://support.astronomer.io
# For issues create an issue ticket here: https://github.com/astronomer/astro-cli/issues

airflow:
  connections:
    - conn_id: getting_json_file
      conn_type: fs
      conn_host:
      conn_schema:
      conn_login:
      conn_password:
      conn_port: 
      conn_extra:
        path: include/data/new
  pools:
    - pool_name:
      pool_slot:
      pool_description:
  variables:
    - variable_name: bot_token
      variable_value: "6122560109:AAFDO_JcwcnmcBpBGqdgwIuj_66cazomTTU"
    - variable_name: chat_id_secret
      variable_value: "1156659572"
    - variable_name: host
      variable_value: postgres
    - variable_name: port
      variable_value: 5432
    - variable_name: database
      variable_value: ensurwave
    - variable_name: username_secret
      variable_value: postgres
    - variable_name: password_secret
      variable_value: postgres